#!/usr/bin/env node
/* ============================================================
   scripts/audit.js — continuous quality audit (run daily)
   Scores every page 0–100, flags issues, writes docs/AUDIT.md,
   exits non-zero if any page is below the quality threshold.
   ============================================================ */
"use strict";

const fs = require("fs");
const path = require("path");

const { auditSite } = require("../services/quality");

const ROOT = path.join(__dirname, "..", "..");
const PUBLIC = path.join(ROOT, "public");
const THRESHOLD = 70; // no page below this without a fix

(async () => {
  if (!fs.existsSync(PUBLIC)) {
    console.log("public/ not built — run build first");
    process.exit(1);
  }
  const results = auditSite(PUBLIC);
  results.sort((a, b) => a.overall - b.overall);

  const below = results.filter((r) => r.overall < THRESHOLD);
  const avg = Math.round(results.reduce((s, r) => s + r.overall, 0) / results.length);

  const lines = [];
  lines.push(`# Quality Audit Report — ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push(`**Pages scored:** ${results.length} · **Average score:** ${avg}/100 · **Below threshold (${THRESHOLD}):** ${below.length}`);
  lines.push("");
  lines.push("## Lowest-scoring pages (top 10)");
  lines.push("");
  lines.push("| Page | Score | Top issues |");
  lines.push("|---|---|---|");
  for (const r of results.slice(0, 10)) {
    lines.push(`| ${r.page} | ${r.overall} | ${r.issues.slice(0, 3).join("; ") || "ok"} |`);
  }
  if (below.length) {
    lines.push("");
    lines.push("## ❌ Pages below threshold (need fixes)");
    for (const r of below) {
      lines.push(`- **${r.page}** (${r.overall}/100): ${r.issues.join("; ")}`);
    }
  } else {
    lines.push("");
    lines.push("✅ All pages above quality threshold.");
  }
  lines.push("");
  lines.push("_Auto-generated by scripts/audit.js — fix issues before major deploys._");

  fs.writeFileSync(path.join(ROOT, "docs", "AUDIT.md"), lines.join("\n"));
  console.log(`Audit: ${results.length} pages, avg ${avg}/100, ${below.length} below ${THRESHOLD}`);
  console.log(`Report → docs/AUDIT.md`);

  // also print scores inline
  for (const r of results.slice(0, 8)) {
    console.log(`  ${r.overall.toString().padStart(3)}  ${r.page}`);
  }
  process.exit(below.length ? 1 : 0);
})();
